apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-slack
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: my-secretstore
    kind: ClusterSecretStore
  target:
    name: external-secrets-webhook
    creationPolicy: Owner
  data:
    - secretKey: slack-webhook-url
      remoteRef:
        key: prod/alertmanager/slack
        property: slack-webhook-url
